require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Admin::AboutsController, type: :controller do

  let(:user) { Signup::User.create(firstname: 'Rails', lastname: 'Admin', email:'a@s.com',password: 'secret', admin: true) }

  before do
    log_in_as user
  end

  # This should return the minimal set of attributes required to create a valid
  # Admin::About. As you add validations to Admin::About, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    {
      slug: 'about us',
      description: 'This is about us page'
    }
  end
  let(:invalid_attributes) do
    {
      slug: '',
      description: ''
    }
  end
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Admin::AboutsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all admin_abouts as @admin_abouts" do
      about = Admin::About.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:admin_abouts)).to eq([about])
    end
  end

  describe "GET #show" do
    it "assigns the requested admin_about as @admin_about" do
      about = Admin::About.create! valid_attributes
      get :show, params: {id: about.to_param}, session: valid_session
      expect(assigns(:admin_about)).to eq(about)
    end
  end

  describe "GET #new" do
    it "assigns a new admin_about as @admin_about" do
      get :new, params: {}, session: valid_session
      expect(assigns(:admin_about)).to be_a_new(Admin::About)
    end
  end

  describe "GET #edit" do
    it "assigns the requested admin_about as @admin_about" do
      about = Admin::About.create! valid_attributes
      get :edit, params: {id: about.to_param}, session: valid_session
      expect(assigns(:admin_about)).to eq(about)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Admin::About" do
        expect {
          post :create, params: {admin_about: valid_attributes}, session: valid_session
        }.to change(Admin::About, :count).by(1)
      end

      it "assigns a newly created admin_about as @admin_about" do
        post :create, params: {admin_about: valid_attributes}, session: valid_session
        expect(assigns(:admin_about)).to be_a(Admin::About)
        expect(assigns(:admin_about)).to be_persisted
      end

      it "redirects to the created admin_about" do
        post :create, params: {admin_about: valid_attributes}, session: valid_session
        expect(response).to redirect_to(Admin::About.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved admin_about as @admin_about" do
        post :create, params: {admin_about: invalid_attributes}, session: valid_session
        expect(assigns(:admin_about)).to be_a_new(Admin::About)
      end

      it "re-renders the 'new' template" do
        post :create, params: {admin_about: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) do
        {

          slug: 'About me',
          description: 'This is updated about page.'

        }
      end

      it "updates the requested admin_about" do
        about = Admin::About.create! valid_attributes
        put :update, params: {id: about.to_param, admin_about: new_attributes}, session: valid_session
        about.reload

      end

      it "assigns the requested admin_about as @admin_about" do
        about = Admin::About.create! valid_attributes
        put :update, params: {id: about.to_param, admin_about: valid_attributes}, session: valid_session
        expect(assigns(:admin_about)).to eq(about)
      end

      it "redirects to the admin_about" do
        about = Admin::About.create! valid_attributes
        put :update, params: {id: about.to_param, admin_about: valid_attributes}, session: valid_session
        expect(response).to redirect_to(about)
      end
    end

    context "with invalid params" do
      it "assigns the admin_about as @admin_about" do
        about = Admin::About.create! valid_attributes
        put :update, params: {id: about.to_param, admin_about: invalid_attributes}, session: valid_session
        expect(assigns(:admin_about)).to eq(about)
      end

      it "re-renders the 'edit' template" do
        about = Admin::About.create! valid_attributes
        put :update, params: {id: about.to_param, admin_about: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested admin_about" do
      about = Admin::About.create! valid_attributes
      expect {
        delete :destroy, params: {id: about.to_param}, session: valid_session
      }.to change(Admin::About, :count).by(-1)
    end

    it "redirects to the admin_abouts list" do
      about = Admin::About.create! valid_attributes
      delete :destroy, params: {id: about.to_param}, session: valid_session
      expect(response).to redirect_to(admin_abouts_url)
    end
  end

end
