require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Admin::EventsController, type: :controller do

  let(:user) { Signup::User.create(firstname: 'Rails', lastname: 'Admin', email:'a@s.com',password: 'secret', admin: true) }

  before do
    log_in_as user
  end

  # This should return the minimal set of attributes required to create a valid
  # Admin::Event. As you add validations to Admin::Event, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do{
    name: "MyString",
    details: "MyText",
    event_date: "2016-11-09",
    starting_time: "MyString",
    ending_time: "MyString",
    place:"Mystring",
    icon: FactoryGirl.create(:admin_icon)
  }end

  let(:invalid_attributes)do {
    name: "MyString",
    details: "",
    event_date: "",
    starting_time: "",
    ending_time: "",
    place:"",
    icon: ''
  }end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Admin::EventsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all admin_events as @admin_events" do
      event = Admin::Event.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:admin_events)).to eq([event])
    end
  end

  describe "GET #show" do
    it "assigns the requested admin_event as @admin_event" do
      event = Admin::Event.create! valid_attributes
      get :show, params: {id: event.to_param}, session: valid_session
      expect(assigns(:admin_event)).to eq(event)
    end
  end

  describe "GET #new" do
    it "assigns a new admin_event as @admin_event" do
      get :new, params: {}, session: valid_session
      expect(assigns(:admin_event)).to be_a_new(Admin::Event)
    end
  end

  describe "GET #edit" do
    it "assigns the requested admin_event as @admin_event" do
      event = Admin::Event.create! valid_attributes
      get :edit, params: {id: event.to_param}, session: valid_session
      expect(assigns(:admin_event)).to eq(event)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Admin::Event" do
        expect {
          Admin::Event.create!(valid_attributes)
        }.to change(Admin::Event, :count).by(1)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved admin_event as @admin_event" do
        post :create, params: {admin_event: invalid_attributes}, session: valid_session
        expect(assigns(:admin_event)).to be_a_new(Admin::Event)
      end

      it "re-renders the 'new' template" do
        post :create, params: {admin_event: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) do{
        name: "MyString1",
            event_date: "2016-11-08",
            starting_time: "MyString1",
        ending_time: "MyString1",
        place:"Mystring",
            icon: FactoryGirl.create(:admin_icon,:name => "az",:icon=>"icon1")
      }end

      it "updates the requested admin_event" do
        event = Admin::Event.create! valid_attributes
        put :update, params: {id: event.to_param, admin_event: new_attributes}, session: valid_session
        event.reload

      end

      it "assigns the requested admin_event as @admin_event" do
        event = Admin::Event.create! valid_attributes
        put :update, params: {id: event.to_param, admin_event: valid_attributes}, session: valid_session
        expect(assigns(:admin_event)).to eq(event)
      end

      it "redirects to the admin_event" do
        event = Admin::Event.create! valid_attributes
        put :update, params: {id: event.to_param, admin_event: valid_attributes}, session: valid_session
        expect(response).to redirect_to(event)
      end
    end

    context "with invalid params" do
      it "assigns the admin_event as @admin_event" do
        event = Admin::Event.create! valid_attributes
        put :update, params: {id: event.to_param, admin_event: invalid_attributes}, session: valid_session
        expect(assigns(:admin_event)).to eq(event)
      end

      it "re-renders the 'edit' template" do
        event = Admin::Event.create! valid_attributes
        put :update, params: {id: event.to_param, admin_event: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested admin_event" do
      event = Admin::Event.create! valid_attributes
      expect {
        delete :destroy, params: {id: event.to_param}, session: valid_session
      }.to change(Admin::Event, :count).by(-1)
    end

    it "redirects to the admin_events list" do
      event = Admin::Event.create! valid_attributes
      delete :destroy, params: {id: event.to_param}, session: valid_session
      expect(response).to redirect_to(admin_events_url)
    end
  end

end
