require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Admin::GoogleMapsController, type: :controller do

  let(:user) { Signup::User.create(firstname: 'Rails', lastname: 'Admin', email:'a@s.com',password: 'secret', admin: true) }

  before do
    log_in_as user
  end

  # This should return the minimal set of attributes required to create a valid
  # Admin::GoogleMap. As you add validations to Admin::GoogleMap, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes)do {
      name: "MyString",
  latitude: "MyString",
  longitude: "MyString",
  google_api_key: "MyString"
  }end

  let(:invalid_attributes) do {
      name: "",
      latitude: "",
      longitude: "",
      google_api_key: ""
  }end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Admin::GoogleMapsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all admin_google_maps as @admin_google_maps" do
      google_map = Admin::GoogleMap.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:admin_google_maps)).to eq([google_map])
    end
  end

  describe "GET #show" do
    it "assigns the requested admin_google_map as @admin_google_map" do
      google_map = Admin::GoogleMap.create! valid_attributes
      get :show, params: {id: google_map.to_param}, session: valid_session
      expect(assigns(:admin_google_map)).to eq(google_map)
    end
  end

  describe "GET #new" do
    it "assigns a new admin_google_map as @admin_google_map" do
      get :new, params: {}, session: valid_session
      expect(assigns(:admin_google_map)).to be_a_new(Admin::GoogleMap)
    end
  end

  describe "GET #edit" do
    it "assigns the requested admin_google_map as @admin_google_map" do
      google_map = Admin::GoogleMap.create! valid_attributes
      get :edit, params: {id: google_map.to_param}, session: valid_session
      expect(assigns(:admin_google_map)).to eq(google_map)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Admin::GoogleMap" do
        expect {
          post :create, params: {admin_google_map: valid_attributes}, session: valid_session
        }.to change(Admin::GoogleMap, :count).by(1)
      end

      it "assigns a newly created admin_google_map as @admin_google_map" do
        post :create, params: {admin_google_map: valid_attributes}, session: valid_session
        expect(assigns(:admin_google_map)).to be_a(Admin::GoogleMap)
        expect(assigns(:admin_google_map)).to be_persisted
      end

      it "redirects to the created admin_google_map" do
        post :create, params: {admin_google_map: valid_attributes}, session: valid_session
        expect(response).to redirect_to(Admin::GoogleMap.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved admin_google_map as @admin_google_map" do
        post :create, params: {admin_google_map: invalid_attributes}, session: valid_session
        expect(assigns(:admin_google_map)).to be_a_new(Admin::GoogleMap)
      end

      it "re-renders the 'new' template" do
        post :create, params: {admin_google_map: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) do {
          name: "MyString1",
          latitude: "MyString1",
          longitude: "MyString1",
          google_api_key: "MyString1"
      }end

      it "updates the requested admin_google_map" do
        google_map = Admin::GoogleMap.create! valid_attributes
        put :update, params: {id: google_map.to_param, admin_google_map: new_attributes}, session: valid_session
        google_map.reload
      end

      it "assigns the requested admin_google_map as @admin_google_map" do
        google_map = Admin::GoogleMap.create! valid_attributes
        put :update, params: {id: google_map.to_param, admin_google_map: valid_attributes}, session: valid_session
        expect(assigns(:admin_google_map)).to eq(google_map)
      end

      it "redirects to the admin_google_map" do
        google_map = Admin::GoogleMap.create! valid_attributes
        put :update, params: {id: google_map.to_param, admin_google_map: valid_attributes}, session: valid_session
        expect(response).to redirect_to(google_map)
      end
    end

    context "with invalid params" do
      it "assigns the admin_google_map as @admin_google_map" do
        google_map = Admin::GoogleMap.create! valid_attributes
        put :update, params: {id: google_map.to_param, admin_google_map: invalid_attributes}, session: valid_session
        expect(assigns(:admin_google_map)).to eq(google_map)
      end

      it "re-renders the 'edit' template" do
        google_map = Admin::GoogleMap.create! valid_attributes
        put :update, params: {id: google_map.to_param, admin_google_map: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested admin_google_map" do
      google_map = Admin::GoogleMap.create! valid_attributes
      expect {
        delete :destroy, params: {id: google_map.to_param}, session: valid_session
      }.to change(Admin::GoogleMap, :count).by(-1)
    end

    it "redirects to the admin_google_maps list" do
      google_map = Admin::GoogleMap.create! valid_attributes
      delete :destroy, params: {id: google_map.to_param}, session: valid_session
      expect(response).to redirect_to(admin_google_maps_url)
    end
  end

end
