require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Admin::QuickLinksController, type: :controller do

  let(:user) { Signup::User.create(firstname: 'Rails', lastname: 'Admin', email:'a@s.com',password: 'secret', admin: true) }

  before do
    log_in_as user
  end

  # This should return the minimal set of attributes required to create a valid
  # Admin::QuickLink. As you add validations to Admin::QuickLink, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do{
      name:"MyString",
      link: "MyString"
  }end

  let(:invalid_attributes)do {
    name:"",
    link: ""
  }end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Admin::QuickLinksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all admin_quick_links as @admin_quick_links" do
      quick_link = Admin::QuickLink.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:admin_quick_links)).to eq([quick_link])
    end
  end

  describe "GET #show" do
    it "assigns the requested admin_quick_link as @admin_quick_link" do
      quick_link = Admin::QuickLink.create! valid_attributes
      get :show, params: {id: quick_link.to_param}, session: valid_session
      expect(assigns(:admin_quick_link)).to eq(quick_link)
    end
  end

  describe "GET #new" do
    it "assigns a new admin_quick_link as @admin_quick_link" do
      get :new, params: {}, session: valid_session
      expect(assigns(:admin_quick_link)).to be_a_new(Admin::QuickLink)
    end
  end

  describe "GET #edit" do
    it "assigns the requested admin_quick_link as @admin_quick_link" do
      quick_link = Admin::QuickLink.create! valid_attributes
      get :edit, params: {id: quick_link.to_param}, session: valid_session
      expect(assigns(:admin_quick_link)).to eq(quick_link)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Admin::QuickLink" do
        expect {
          post :create, params: {admin_quick_link: valid_attributes}, session: valid_session
        }.to change(Admin::QuickLink, :count).by(1)
      end

      it "assigns a newly created admin_quick_link as @admin_quick_link" do
        post :create, params: {admin_quick_link: valid_attributes}, session: valid_session
        expect(assigns(:admin_quick_link)).to be_a(Admin::QuickLink)
        expect(assigns(:admin_quick_link)).to be_persisted
      end

      it "redirects to the created admin_quick_link" do
        post :create, params: {admin_quick_link: valid_attributes}, session: valid_session
        expect(response).to redirect_to(Admin::QuickLink.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved admin_quick_link as @admin_quick_link" do
        post :create, params: {admin_quick_link: invalid_attributes}, session: valid_session
        expect(assigns(:admin_quick_link)).to be_a_new(Admin::QuickLink)
      end

      it "re-renders the 'new' template" do
        post :create, params: {admin_quick_link: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes)do {
        name:"MyString1",
        link: "MyString1"
      }end

      it "updates the requested admin_quick_link" do
        quick_link = Admin::QuickLink.create! valid_attributes
        put :update, params: {id: quick_link.to_param, admin_quick_link: new_attributes}, session: valid_session
        quick_link.reload
      end

      it "assigns the requested admin_quick_link as @admin_quick_link" do
        quick_link = Admin::QuickLink.create! valid_attributes
        put :update, params: {id: quick_link.to_param, admin_quick_link: valid_attributes}, session: valid_session
        expect(assigns(:admin_quick_link)).to eq(quick_link)
      end

      it "redirects to the admin_quick_link" do
        quick_link = Admin::QuickLink.create! valid_attributes
        put :update, params: {id: quick_link.to_param, admin_quick_link: valid_attributes}, session: valid_session
        expect(response).to redirect_to(quick_link)
      end
    end

    context "with invalid params" do
      it "assigns the admin_quick_link as @admin_quick_link" do
        quick_link = Admin::QuickLink.create! valid_attributes
        put :update, params: {id: quick_link.to_param, admin_quick_link: invalid_attributes}, session: valid_session
        expect(assigns(:admin_quick_link)).to eq(quick_link)
      end

      it "re-renders the 'edit' template" do
        quick_link = Admin::QuickLink.create! valid_attributes
        put :update, params: {id: quick_link.to_param, admin_quick_link: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested admin_quick_link" do
      quick_link = Admin::QuickLink.create! valid_attributes
      expect {
        delete :destroy, params: {id: quick_link.to_param}, session: valid_session
      }.to change(Admin::QuickLink, :count).by(-1)
    end

    it "redirects to the admin_quick_links list" do
      quick_link = Admin::QuickLink.create! valid_attributes
      delete :destroy, params: {id: quick_link.to_param}, session: valid_session
      expect(response).to redirect_to(admin_quick_links_url)
    end
  end

end
