require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Admin::SemestersController, type: :controller do

  let(:user) { Signup::User.create(firstname: 'Rails', lastname: 'Admin', email:'a@s.com',password: 'secret', admin: true) }

  before do
    log_in_as user
  end

  # This should return the minimal set of attributes required to create a valid
  # Admin::Semester. As you add validations to Admin::Semester, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do {

      name: 'first semester',
      short_form: '1st'
  }
  end
  let(:invalid_attributes) do {

      name: '',
      short_form: ''
  }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Admin::SemestersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all admin_semesters as @admin_semesters" do
      semester = Admin::Semester.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:admin_semesters)).to eq([semester])
    end
  end

  describe "GET #show" do
    it "assigns the requested admin_semester as @admin_semester" do
      semester = Admin::Semester.create! valid_attributes
      get :show, params: {id: semester.to_param}, session: valid_session
      expect(assigns(:admin_semester)).to eq(semester)
    end
  end

  describe "GET #new" do
    it "assigns a new admin_semester as @admin_semester" do
      get :new, params: {}, session: valid_session
      expect(assigns(:admin_semester)).to be_a_new(Admin::Semester)
    end
  end

  describe "GET #edit" do
    it "assigns the requested admin_semester as @admin_semester" do
      semester = Admin::Semester.create! valid_attributes
      get :edit, params: {id: semester.to_param}, session: valid_session
      expect(assigns(:admin_semester)).to eq(semester)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Admin::Semester" do
        expect {
          post :create, params: {admin_semester: valid_attributes}, session: valid_session
        }.to change(Admin::Semester, :count).by(1)
      end

      it "assigns a newly created admin_semester as @admin_semester" do
        post :create, params: {admin_semester: valid_attributes}, session: valid_session
        expect(assigns(:admin_semester)).to be_a(Admin::Semester)
        expect(assigns(:admin_semester)).to be_persisted
      end

      it "redirects to the created admin_semester" do
        post :create, params: {admin_semester: valid_attributes}, session: valid_session
        expect(response).to redirect_to(Admin::Semester.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved admin_semester as @admin_semester" do
        post :create, params: {admin_semester: invalid_attributes}, session: valid_session
        expect(assigns(:admin_semester)).to be_a_new(Admin::Semester)
      end

      it "re-renders the 'new' template" do
        post :create, params: {admin_semester: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) do {

          name: '2nd Semester',
          short_form: '2nd'
      }
      end


      it "updates the requested admin_semester" do
        semester = Admin::Semester.create! valid_attributes
        put :update, params: {id: semester.to_param, admin_semester: new_attributes}, session: valid_session
        semester.reload

      end

      it "assigns the requested admin_semester as @admin_semester" do
        semester = Admin::Semester.create! valid_attributes
        put :update, params: {id: semester.to_param, admin_semester: valid_attributes}, session: valid_session
        expect(assigns(:admin_semester)).to eq(semester)
      end

      it "redirects to the admin_semester" do
        semester = Admin::Semester.create! valid_attributes
        put :update, params: {id: semester.to_param, admin_semester: valid_attributes}, session: valid_session
        expect(response).to redirect_to(semester)
      end
    end

    context "with invalid params" do
      it "assigns the admin_semester as @admin_semester" do
        semester = Admin::Semester.create! valid_attributes
        put :update, params: {id: semester.to_param, admin_semester: invalid_attributes}, session: valid_session
        expect(assigns(:admin_semester)).to eq(semester)
      end

      it "re-renders the 'edit' template" do
        semester = Admin::Semester.create! valid_attributes
        put :update, params: {id: semester.to_param, admin_semester: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested admin_semester" do
      semester = Admin::Semester.create! valid_attributes
      expect {
        delete :destroy, params: {id: semester.to_param}, session: valid_session
      }.to change(Admin::Semester, :count).by(-1)
    end

    it "redirects to the admin_semesters list" do
      semester = Admin::Semester.create! valid_attributes
      delete :destroy, params: {id: semester.to_param}, session: valid_session
      expect(response).to redirect_to(admin_semesters_url)
    end
  end

end
