require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Admin::SocialMediaController, type: :controller do

  let(:user) { Signup::User.create(firstname: 'Rails', lastname: 'Admin', email:'a@s.com',password: 'secret', admin: true) }

  before do
    log_in_as user
  end

  # This should return the minimal set of attributes required to create a valid
  # Admin::SocialMedium. As you add validations to Admin::SocialMedium, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes)do{
      name: "MyString",
  link: "MyString",
      icon: FactoryGirl.create(:admin_icon)
  }end

  let(:invalid_attributes) do{
      name: "",
      link: "",
      icon: ""
  }end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Admin::SocialMediaController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all admin_social_media as @admin_social_media" do
      social_medium = Admin::SocialMedium.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:admin_social_media)).to eq([social_medium])
    end
  end

  describe "GET #show" do
    it "assigns the requested admin_social_medium as @admin_social_medium" do
      social_medium = Admin::SocialMedium.create! valid_attributes
      get :show, params: {id: social_medium.to_param}, session: valid_session
      expect(assigns(:admin_social_medium)).to eq(social_medium)
    end
  end

  describe "GET #new" do
    it "assigns a new admin_social_medium as @admin_social_medium" do
      get :new, params: {}, session: valid_session
      expect(assigns(:admin_social_medium)).to be_a_new(Admin::SocialMedium)
    end
  end

  describe "GET #edit" do
    it "assigns the requested admin_social_medium as @admin_social_medium" do
      social_medium = Admin::SocialMedium.create! valid_attributes
      get :edit, params: {id: social_medium.to_param}, session: valid_session
      expect(assigns(:admin_social_medium)).to eq(social_medium)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Admin::SocialMedium" do
        expect {
          Admin::SocialMedium.create!(valid_attributes)
              .to change(Admin::SocialMedium, :count).by(1)}
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved admin_social_medium as @admin_social_medium" do
        post :create, params: {admin_social_medium: invalid_attributes}, session: valid_session
        expect(assigns(:admin_social_medium)).to be_a_new(Admin::SocialMedium)
      end

      it "re-renders the 'new' template" do
        post :create, params: {admin_social_medium: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) do{
        name: "MyString",
            link: "MyString",
        icon: FactoryGirl.create(:admin_icon, name: "MyString2",:icon=>"icon2")
      }end

      it "updates the requested admin_social_medium" do
        social_medium = Admin::SocialMedium.create! valid_attributes
        put :update, params: {id: social_medium.to_param, admin_social_medium: new_attributes}, session: valid_session
        social_medium.reload
      end

      it "assigns the requested admin_social_medium as @admin_social_medium" do
        social_medium = Admin::SocialMedium.create! valid_attributes
        put :update, params: {id: social_medium.to_param, admin_social_medium: valid_attributes}, session: valid_session
        expect(assigns(:admin_social_medium)).to eq(social_medium)
      end

      it "redirects to the admin_social_medium" do
        social_medium = Admin::SocialMedium.create! valid_attributes
        put :update, params: {id: social_medium.to_param, admin_social_medium: valid_attributes}, session: valid_session
        expect(response).to redirect_to(social_medium)
      end
    end

    context "with invalid params" do
      it "assigns the admin_social_medium as @admin_social_medium" do
        social_medium = Admin::SocialMedium.create! valid_attributes
        put :update, params: {id: social_medium.to_param, admin_social_medium: invalid_attributes}, session: valid_session
        expect(assigns(:admin_social_medium)).to eq(social_medium)
      end

      it "re-renders the 'edit' template" do
        social_medium = Admin::SocialMedium.create! valid_attributes
        put :update, params: {id: social_medium.to_param, admin_social_medium: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested admin_social_medium" do
      social_medium = Admin::SocialMedium.create! valid_attributes
      expect {
        delete :destroy, params: {id: social_medium.to_param}, session: valid_session
      }.to change(Admin::SocialMedium, :count).by(-1)
    end

    it "redirects to the admin_social_media list" do
      social_medium = Admin::SocialMedium.create! valid_attributes
      delete :destroy, params: {id: social_medium.to_param}, session: valid_session
      expect(response).to redirect_to(admin_social_media_url)
    end
  end

end
