require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe SlidersController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Slider. As you add validations to Slider, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SlidersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all sliders as @sliders" do
      slider = Slider.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:sliders)).to eq([slider])
    end
  end

  describe "GET #show" do
    it "assigns the requested slider as @slider" do
      slider = Slider.create! valid_attributes
      get :show, params: {id: slider.to_param}, session: valid_session
      expect(assigns(:slider)).to eq(slider)
    end
  end

  describe "GET #new" do
    it "assigns a new slider as @slider" do
      get :new, params: {}, session: valid_session
      expect(assigns(:slider)).to be_a_new(Slider)
    end
  end

  describe "GET #edit" do
    it "assigns the requested slider as @slider" do
      slider = Slider.create! valid_attributes
      get :edit, params: {id: slider.to_param}, session: valid_session
      expect(assigns(:slider)).to eq(slider)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Slider" do
        expect {
          post :create, params: {slider: valid_attributes}, session: valid_session
        }.to change(Slider, :count).by(1)
      end

      it "assigns a newly created slider as @slider" do
        post :create, params: {slider: valid_attributes}, session: valid_session
        expect(assigns(:slider)).to be_a(Slider)
        expect(assigns(:slider)).to be_persisted
      end

      it "redirects to the created slider" do
        post :create, params: {slider: valid_attributes}, session: valid_session
        expect(response).to redirect_to(Slider.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved slider as @slider" do
        post :create, params: {slider: invalid_attributes}, session: valid_session
        expect(assigns(:slider)).to be_a_new(Slider)
      end

      it "re-renders the 'new' template" do
        post :create, params: {slider: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested slider" do
        slider = Slider.create! valid_attributes
        put :update, params: {id: slider.to_param, slider: new_attributes}, session: valid_session
        slider.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested slider as @slider" do
        slider = Slider.create! valid_attributes
        put :update, params: {id: slider.to_param, slider: valid_attributes}, session: valid_session
        expect(assigns(:slider)).to eq(slider)
      end

      it "redirects to the slider" do
        slider = Slider.create! valid_attributes
        put :update, params: {id: slider.to_param, slider: valid_attributes}, session: valid_session
        expect(response).to redirect_to(slider)
      end
    end

    context "with invalid params" do
      it "assigns the slider as @slider" do
        slider = Slider.create! valid_attributes
        put :update, params: {id: slider.to_param, slider: invalid_attributes}, session: valid_session
        expect(assigns(:slider)).to eq(slider)
      end

      it "re-renders the 'edit' template" do
        slider = Slider.create! valid_attributes
        put :update, params: {id: slider.to_param, slider: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested slider" do
      slider = Slider.create! valid_attributes
      expect {
        delete :destroy, params: {id: slider.to_param}, session: valid_session
      }.to change(Slider, :count).by(-1)
    end

    it "redirects to the sliders list" do
      slider = Slider.create! valid_attributes
      delete :destroy, params: {id: slider.to_param}, session: valid_session
      expect(response).to redirect_to(sliders_url)
    end
  end

end
